export const screens = {
  Home: 'HomeScreen',
  Settings: 'SettingsScreen',
  LearnMoreLinks: 'LearnMoreLinksScreen',
  LearnWithImages: 'LearnWithImagesScreen',
  SelectSet: 'SelectSetScreen',
  SelectLevel: 'SelectLevelScreen',
  LearnWithQuiz: 'LearnWithQuiz',
  NewsPaper: 'NewsPaper',
  AboutUs: 'AboutUsScreen',
  PrivacyPolicy: 'PrivacyPolicyScreen',
  TermsConditions: 'TermsConditionsScreen',
  Instruction: 'InstructionScreen',
  SelectMock: 'SelectMockScreen',
  MockTest: 'MockTestScreen',
  CurrentAffairs: 'CurrentAffairsScreen',
  PDFView: 'PDFViewScreen',
  MonthListing: 'MonthListingScreen',
  MCQListing: 'MCQListingScreen',
  MSQQuestion: 'MSQQuestionScreen',
  Score: 'ScoreScreen',
};
